OOP School Library #3: Association
miltonHenschel/oop-school-library pull request #4
Opened 2023-04-28 01:35 UTC by miltonHenschel

- [ ] Create a class Classroom with the following:

  - @label instance variable, should be initialized in the constructor.
  - Setter and getter for @label (remember about attr_accessor).

- [ ] Create the has-many/belongs-to relationship between Classroom and Student. The following should be implemented:

  - Create the has-many side (a classroom has many students).
  - Create the belongs-to side (a student belongs to a classroom).
  - Make sure that when adding a student to a classroom it also sets the classroom for the student.
  - Make sure that when setting the classroom for a student it also adds it to the classrooms' students.

- [ ] Create a class Book with the following:

  - @title and @author instance variables, should be initialized in the constructor.
  - Setters and getters for instance variables (remember about attr_accessor).

- [ ] Create a class Rental with the following:

  - @date instance variable, should be initialized in the constructor.
  - Setter and getter for @date (remember about attr_accessor).

- [ ] Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental. The following should be implemented:

  - Create the has-many side of Book and Rental (a book has many rentals).
  - Create the belongs-to side of Rental and Book (a rental belongs to a book).
  - Create the has-many side of Person and Rental (a person has many rentals).
  - Create the belongs-to side of Rental and Person (a rental belongs to a person).
  - Modify the constructor of Rental so Book and Person are set in it.

2023-04-28 02:26 UTC, Owusu-Desmond requested changes
Hi @miltonHenschel , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that does not have a descriptive and summarised PR description. make sure you state what you have implemented instead of copying project requirements and pasting them as your PR description. :smile: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-28 04:35 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @miltonHenschel , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Great use of getter and setter shortcut method
:heavy_check_mark: Descriptive Readme file and PR
:heavy_check_mark: Linter checks passing

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing the first letters of your commit messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 04:35 UTC, t-yanick commented on book.rb
> +  attr_reader :rentals
- [ ] Great job working on this milestone. `Getter` and `setter` methods should be present for the `rentals` variable. This is because for rentals, we need to access the value of this instance variable and also at another instance, we would need to change or sent the value of the instance variable rentals. You can simply delete `line 3 `and add rentals to the shortcut method with title and author.
![Screen Shot 2023-04-27 at 9 21 53 PM](https://user-images.githubusercontent.com/62849872/235053493-473545f5-0c4b-4fb3-ba8e-604bf8d13414.png)

2023-04-28 04:35 UTC, t-yanick commented on rental.rb
> +  attr_reader :person, :book
- [ ] Same issue I pointed out in the book class for the rentals instance varriable should be applied to the person and book instance variables. Getters and setters should be present for the same reason raised up.
![Screen Shot 2023-04-27 at 9 25 50 PM](https://user-images.githubusercontent.com/62849872/235053990-d6e41201-fd31-44dd-bd0d-a7a74e7dd576.png)

2023-04-28 04:35 UTC, t-yanick commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Getter and setter methods should be present for the rentals variable. This is because for rentals, we need to access the value of this instance variable and also at another instance, we would need to change or sent the value of the instance variable rentals.
![Screen Shot 2023-04-27 at 9 27 49 PM](https://user-images.githubusercontent.com/62849872/235054307-9c58107f-6374-4fae-abb5-cbd70f78b555.png)

2023-04-28 08:27 UTC, miltonHenschel commented on person.rb
> +  attr_reader :id, :rentals
Wow! Thanks for all your keen remarks. I'll implement it without fail!

2023-04-28 10:02 UTC, jerryowusu approved these changes
Hi @miltonHenschel  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![CookedDelectableDolphin-size_restricted](https://user-images.githubusercontent.com/65233860/235118422-b1ede685-e9c7-43df-87fe-7c5fe68465f2.gif)


## Highlights
Great effort in making the requested changes :+1: 
Used correct Gitflow :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 10:03 UTC, miltonHenschel commented
Thanks very @jerryowusu.

2023-04-28 10:04 UTC, merged

2023-06-22 08:11 UTC, AmaduKamara reviewed
# Status: APPROVED 🟢 🟢 🟢

Hi @miltonHenschel,

Your project is complete! There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ Good job working on the changes and the project has been approved 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```